# https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel
cache: packages
warnings_are_errors: false
latex: false

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

bioc_packages:
  - Biobase




