# https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
      warnings_are_errors: false
    - os: osx
      r: release

